### ISSUE TITLE
Crash when searching up Pickle Tweaks Items in JEI

### ISSUE THREAD

**Issue by Zer0Lyfe** [BlakeBr0/PickleTweaks2#1]
So I tried searching for @pickle but when I did. It crashed.
Sorry that this file is so large. It is 1.5mb big so I cant post it on a paste website.
and the version of Jei: jei_1.12.2-4.8.0.109
[Large.txt](https://github.com/BlakeBr0/PickleTweaks2/files/1403873/Large.txt)

**Comment by BlakeBr0** [comment]
Did you disable repair kits?
