### ISSUE TITLE
Error. Exception loading model for variant [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [BlakeBr0/PickleTweaks2#11]
Minecraft: 1.12.2
Forge: all (last 14.23.2.2640)
PickleTweaks 2.0.11
Cucumber 1.0.4
Lines:
10980
11005
Debug Log - https://drive.google.com/open?id=1ylMdlIfBFCI-GLKlclPMSj_HubkuYMpz

**Comment by BlakeBr0** [comment]
That's not a big deal. I'm assuming you haven't added any of your own repair kits.

**Comment by kellixon** [comment]
True. I use the default.
