### ISSUE TITLE
[1.12.2] Dedicated server crash with latest Pickletweaks and Cucumber

### ISSUE THREAD

**Issue by kwpugh** [BlakeBr0/PickleTweaks2#13]
Crash report: https://gist.github.com/kwpugh/dcddb97fdbe81256e0e68ff72a911933

Forge: forge-1.12.2-14.23.2.2641-installer.jar
Mod: cucumber-1.12-1.1.0.jar & pickletweaks-1.12-2.0.12.jar

**Comment by BlakeBr0** [comment]
Do you know which mod update caused this to happen?

**Comment by kwpugh** [comment]
I believe it was fine before I updated to the latest cucumber, I believe 1.0.4 was ok with the latest tweaks.

**Comment by BlakeBr0** [comment]
I think its pickletweaks since I get the crash in my dev environment with cucumber 1.0.2. What version were you on before updating to .12?

**Comment by BlakeBr0** [comment]
Nevermind I think I found the issue
