### ISSUE TITLE
Resource Pack support

### ISSUE THREAD

**Issue by Seth0067** [BlakeBr0/PickleTweaks2#15]
Hi BlakeBr0, 

I am making a Sphax BDCraft patch for PickleTweaks (part of a pack patch for Craft of the Titans II) and wanted to know if you could actually use different assets for the various repair kit options.  This way, I can make item textures for them in the resource pack.  If there's another way to do this, I am open to ideas.  

Here's the item sample at 128x:

![repair_kit](https://user-images.githubusercontent.com/22122348/38970651-8b79c5a8-434b-11e8-8120-763fe4b6ae78.png)

**Comment by BlakeBr0** [comment]
There isn't really a need to give them individual textures, just make a grey one and it'll get recolored. Even if I were to use separate textures for each kit, I would still need to keep the current system for the custom repair kits.

One thing I could do is make only layer 0 get colored, this would allow for another layer for things that don't need to be colored. It would still be the same texture for every kit though.

**Comment by Seth0067** [comment]
This works quite well actually!  You are brilliant.  Thank you, sir.
