### ISSUE TITLE
404 Meme not found: right clicking chests with a tool that can place torches

### ISSUE THREAD

**Issue by kragnoth** [BlakeBr0/PickleTweaks2#16]
When you right click a chest with a tool that can place torches, the chest does not animate.

Thanks

PepoDance

**Comment by BlakeBr0** [comment]
I think it's ClientTweaks that adds the right clicking to place torches functionality
![pepodance](https://user-images.githubusercontent.com/12994882/39274158-b087c132-48a6-11e8-9fd4-f0d210e2dfb8.gif)

**Comment by kragnoth** [comment]
Oh?  And here I thought all useful functionality came from your mod.  Will check out.  Want me to close this?

**Comment by BlakeBr0** [comment]
It's very rare that good things come from my mods
