### ISSUE TITLE
I can't repair my tools listed in the config for some reason?

### ISSUE THREAD

**Issue by trilexcom** [BlakeBr0/PickleTweaks2#17]
hi BlakeBr0 we are using PickleTweaks 2 in our custom modpack for some reason i can't repair any of the tools listed in my config here is the link to our config file https://gist.github.com/trilexcom/84be607d7eda28cbaef3f89b5e15d030

can you please tell me if i am derping somewhere in the config?  or its a bug ? 

We are using Forge : 2678
MC : 1.12.2
PickleTweaks2 : 2.0.16
PrimalCore: 0.6.52

**Comment by BlakeBr0** [comment]
Looks fine to me, not sure what the issue could be

**Comment by trilexcom** [comment]
let me give you fml logs and client logs so you can check it 

fml server logs https://gist.github.com/trilexcom/a8f27acb5483650799ba63f897bcd858

fml client latest https://gist.github.com/trilexcom/d9451b8e8e3f133c77c010422fe21f48

**Comment by trilexcom** [comment]
i see sevtech is using version 2.0.9 i am going to downgrade it and see if works for me

**Comment by trilexcom** [comment]
after downgrading to 2.09 still not working and this is how i repair tools like right? https://imgur.com/a/it46hqA

just a fyi this is on a server not a single player world

**Comment by BlakeBr0** [comment]
That should work fine, does the server and client have the same configs? Does it work in singleplayer? Does it work with other tools?

**Comment by trilexcom** [comment]
Client and server has the same config I will try single player and get back
to you asap

**Comment by trilexcom** [comment]
it doesn't work in single player either i am trying to making another custom pack with only your mod with vanilla and see it works with this version of forge

**Comment by trilexcom** [comment]
when i make a custom mod with only yours its working fine with primal too, so i think its another mod causing the issue for me i need to investigate more

**Comment by trilexcom** [comment]
closing this issue
