### ISSUE TITLE
[Compatibility] Can't change block hardness or harvest level from somes mods.

### ISSUE THREAD

**Issue by Fireztonez** [BlakeBr0/PickleTweaks2#18]
Hello,
I try to change Mining Level and hardness for somes blocks and ores in my new modpack in development and I noticed that the blocks of several mods were not affected by the changes. WAILA shows that the block is not harvestable, but I can mine it without problems.

Here is a list of some mods that I noticed for the moment that I could not change, while it is absolutely necessary for my modpack;
- Chisel
- Rockhounding Mod: Surface
- Rockhounding Mod: Chemistry
- Rockhounding Mod: Ore Tiers

The list is probably not complete, but this is what I found today!

Do you think you can fix that problem or tel me how I can fix-it. I know with Tool Progression I can change the mining level all that mods, but I can't use that mod, becose is made the block indestructible, if don't have the good tools...

Version:
Minecraft: 1.12.2
Forge: 14.23.3.2678
Pickle Tweaks: 2.0.16
Cucumber: 1.1.0

Thank you very much for you mod, you do a really good job!!
Fireztonez

**Comment by BlakeBr0** [comment]
You might need to specify the tool required to harvest as well, the comments in the config should say how if it's possible

**Comment by Fireztonez** [comment]
Thank's for the reply,
I will test if it work when specify pickaxe for the tool required to harvest and let you know.

**Comment by Fireztonez** [comment]
Look like it works. So we realy need to set the harvest tool for the blocks from some mods... Good to know!

I wonder at the same time, if I want to set multiple type of tool for one item, like a paxle, how can we do with the config? Is it possible??

**Comment by BlakeBr0** [comment]
Not sure what you mean, paxels are all 3 tool types

**Comment by Fireztonez** [comment]
Oki, I will try to make my question more clear...
First;
- Is it possible to change or add a toolclass to an item. By example, one tool I want to change is the Atomic Disassembler of Mekanism, becose is not reconised like a Shovel or Axe, but is a All-In-One tool. That will cause problem in my modpack I'm pretty sure...

Second;
- If is possible to do, how can I add more than one type on a tool?? Do I need to add in multiple line or I need to do in one line??

I hope this is more clear explain like that?
Fireztonez

**Comment by BlakeBr0** [comment]
Not sure if you can add more then one class, could always try it. If it does work you'd have to do a line for each tool class yea

**Comment by Fireztonez** [comment]
I try with the PrimalCore Flint Hatchet and doesn't look like I can change the tool type of the item....

And about the main issue of this issue, I can change the mining level of a block, when add by example "-pickaxe", but for the block_hardness I can't change-it... I don't know if the problem is the fact I try to change hardness to a block with metadata (Doesn't said anything in the notes of that option about the metadata)... 

I test using that:
```
    S:block_hardness <
        rockhounding_surface:bog_logs:2=50
        chisel:marble2:7=100
        minecraft:stone=100
     >
```
And only the stone in this 3 blocks have been change....

**Comment by BlakeBr0** [comment]
The block hardness tweak does not support metadata.
