### ISSUE TITLE
Repair Kit do not support localization

### ISSUE THREAD

**Issue by Snownee** [BlakeBr0/PickleTweaks2#19]
https://github.com/BlakeBr0/PickleTweaks2/blob/a497054d0a62a706ea095f73baccbed35661c288/src/main/java/com/blakebr0/pickletweaks/feature/item/ItemRepairKit.java#L41

**Comment by BlakeBr0** [comment]
Do you mean localization for the name given in the config? Didn't really think that was needed.

**Comment by Snownee** [comment]
Config,? Are they from config? I mean the material name.

**Comment by BlakeBr0** [comment]
I see what you mean, I can look into making them localized.
