### ISSUE TITLE
Custom Repair Materials

### ISSUE THREAD

**Issue by MasterEnderman** [BlakeBr0/PickleTweaks2#2]
If you change the repair material of a vanilla tool it can be repaired with booth materials e.g. 

minecraft:iron_pickaxe=ore:nuggetIron

the pickaxe can be repaired with Iron Ingots and with Iron Nuggets.

**Comment by BlakeBr0** [comment]
Yes, thats how it's supposed to work.

**Comment by MasterEnderman** [comment]
Could you make it an option to only allow the defined material and nothing else?
