### ISSUE TITLE
Harvest Level Issue

### ISSUE THREAD

**Issue by NielsPilgaard** [BlakeBr0/PickleTweaks2#20]
I'm trying to change the harvest level of all logs to 1, but I crash on startup with all the possibilities I've tried. 
The crash is nearly always the same: 
https://gist.github.com/NillerMedDild/91ec0e388d8f7f6ae3d4d74b9feb9717

I've tried a lot of different ways, here are some of them, all tried one at a time:
`minecraft:log=1`
`minecraft:log=1-'axe'`
`minecraft:log=1-axe`
`ore:logWood=1`
`ore:logWood=1-axe` - unique crash https://gist.github.com/NillerMedDild/2654599c00cac48598cf653d511b134a
`ore:logWood=1-'axe'`

**Comment by BlakeBr0** [comment]
The first crash is because you arent setting a metadata for the block id, you can use ":*" as a wildcard. I can also look into making that not require meta at all.

Not 100% sure about the oredictionary one atm, I'll have to look into that one.

**Comment by NielsPilgaard** [comment]
Ah, thanks! I'm not used to this kind of config requiring a meta, but I don't mind. I just noticed the `:meta` in the syntax explaination above ^^'

Sounds good.

**Comment by NielsPilgaard** [comment]
The game is able to launch just fine now, but it doesn't seem like the harvest levels of Logs are actually getting changed. I'm able to break Oak Wood with an empty hand, aswell as a Tinkers' Wooden Pickaxe. Here's the config:

    S:harvest_level <
    minecraft:log:*=2-Axe
    minecraft:log2:*=2-Axe
    dynamictrees:oakbranch:0=2-Axe
    dynamictrees:darkoakbranch:0=2-Axe
    dynamictrees:birchbranch:0=2-Axe
    dynamictrees:sprucebranch:0=2-Axe
    dynamictrees:junglebranch:0=2-Axe
    dynamictrees:acaciabranch:0=2-Axe
    dttraverse:firbranch:0=2-Axe
     >

**Comment by BlakeBr0** [comment]
Could be because the tool class is capitalized?

**Comment by NielsPilgaard** [comment]
Changing Axe to axe didn't change anything sadly. Could it be because it doesn't require a tool by default?

**Comment by BlakeBr0** [comment]
If you don't put a required tool does it work? Or putting 'null' as the tool?

**Comment by NielsPilgaard** [comment]
Nope, it's still harvestable by anything.

**Comment by NielsPilgaard** [comment]
It would appear the meta wildcard * doesn't work either.
