### ISSUE TITLE
Missing tooltips in JEI

### ISSUE THREAD

**Issue by kellixon** [BlakeBr0/PickleTweaks2#24]
MC 1.12.2. Forge 14.23.5.2768. All settings all mods default (clear folder config). Missing tooltips in JEI, at Minecraft GUI have. Full logs - https://gist.github.com/kellixon/2e08cec3eb42f5fa26b2c9db26bfeb10.
![2018-11-27_15 28 33](https://user-images.githubusercontent.com/22012731/49082218-47c6f600-f25a-11e8-9727-6fca103ff179.png)

**Comment by kellixon** [comment]
![2018-11-27_15 28 41](https://user-images.githubusercontent.com/22012731/49082219-47c6f600-f25a-11e8-97d0-17b508330389.png)

**Comment by mezz** [comment]
Pickletweaks has a check in their tooltip handler to see if the player is null:
https://github.com/BlakeBr0/PickleTweaks/blob/30f2716b97627af5a818ce85a43dbaf67b1db873/src/main/java/com/blakebr0/pickletweaks/feature/FeatureToolInfo.java#L85

The player is null for JEI to avoid showing valuable tooltips that are only supposed to exist once you have crafted the item.
If Pickletweaks intends to allow these tooltips in JEI, they might want to work around the check for the player being null.
