### ISSUE TITLE
[Suggestion] Only allow custom repair material

### ISSUE THREAD

**Issue by MasterEnderman** [BlakeBr0/PickleTweaks2#3]
As mentioned before (https://github.com/BlakeBr0/PickleTweaks2/issues/2) it would be nice to have a config option to only allow the custom repair material and nothing else.

(created a new issue, because the old one is closed)

**Comment by BlakeBr0** [comment]
So you want a config option to make it so only the repair materials you set work right?

**Comment by BlakeBr0** [comment]
I added a config option to disable all default repair materials. I also added a config to enable "override mode", which makes it so any tool with a custom repair material overrides the default materials entirely.

**Comment by MasterEnderman** [comment]
Exactly what I wanted. Thank you.
