### ISSUE TITLE
Single Charcoal piece does not cook 1 item

### ISSUE THREAD

**Issue by Dyonovan** [BlakeBr0/PickleTweaks2#32]
When I place 2 charcoal pieces and try and cook just 1 item, it starts to burn the second piece of charcoal after it has finished cooking the 1 item.

Using Sky Factory 4 pack.

Any other info needed just let me know. I actually am streaming this so have video footage of this happening.

**Comment by BlakeBr0** [comment]
I didn't test it in sf4 specifically but I don't seem to be having this issue. Maybe it's a pack specific issue or there are some other mods involved?

**Comment by Dyonovan** [comment]
Actually sorry, I meant to close this as the issue seems to be with a slab furnace. The vanilla one seems to be fine. I'm guessing its a rounding issue.
