### ISSUE TITLE
Duplicates items when used with Industrial Foregoing's Plant Interactor

### ISSUE THREAD

**Issue by smitty260** [BlakeBr0/PickleTweaks2#33]
When using this mod with Industrial Foregoing's Plant Interactor machine it duplicates items. The Plant Interactor simulates a right-click on crops and is meant to put the crops into the internal storage or drop them on the ground if it is full. When using Pickle Tweaks with this machine it puts the harvested crops in the internal storage as well as dropping them on the ground essentially duplicating the items.

I talked to the Industrial Foregoing's developer and he said there is nothing he can do so I was hoping that you could fix it from this side. Thanks.

**Comment by BlakeBr0** [comment]
Fixed in the 1.14 version.
