### ISSUE TITLE
[1.14.4-3.0.2] crash while loading

### ISSUE THREAD

**Issue by sarifynna** [BlakeBr0/PickleTweaks2#36]
I had to update forge to at least 28.0.27 for another mod (uteamcore) and suddenly I am crashing on load. It mentions pickle tweaks so I am reporting here.

[crash-2019-08-01_05.06.38-client.txt](https://github.com/BlakeBr0/PickleTweaks/files/3456615/crash-2019-08-01_05.06.38-client.txt)

[2019-08-01-3.log](https://github.com/BlakeBr0/PickleTweaks/files/3456619/2019-08-01-3.log)

**Comment by BlakeBr0** [comment]
I can't reproduce this, even with the latest forge and uteamcore.

**Comment by sarifynna** [comment]
After some time away I updated a few more mods and it's just working now... so either it will be fine or catch on fire later. Sorry for the report if nothing is wrong with pickle tweaks and thanks for such a great mod btw! <3

[latest.log](https://github.com/BlakeBr0/PickleTweaks/files/3461010/latest.log)

edit: It may have actually just been the mod random patches, sorry for the report on here!
