### ISSUE TITLE
[1.14.4] Watering can will not fill on servers

### ISSUE THREAD

**Issue by darkphan** [BlakeBr0/PickleTweaks2#39]
Version: PickleTweaks-1.14.4-3.0.4

After crafting a watering can you can not fill it while on a server, seems to be fine in single player.

**Comment by darkphan** [comment]
It seemed to be a conflict with a mod. I removed (for other reasons) FastWorkbench, FastFurnace and Colytra and noticed after doing that it was working.

**Comment by hron84** [comment]
@BlakeBr0 please reopen, it does not work without Fast* mods or Colytra. Needs more investigation.
