### ISSUE TITLE
Can't seem to find a complete reference config?

### ISSUE THREAD

**Issue by MarcosCosmos** [BlakeBr0/PickleTweaks2#42]
I noticed that "Everything can be disabled in config" and that the configuration is extensive - I've seen a snippet in another issue relating repair recipes for example. But I can't seem to find an endorsed full configuration example. The default configuration created in my server is far from complete (e.g. doesn't have any repair kits or custom materials).

This seems to be a common but undiscussed issue across a lot of mods I've been looking at - each with some apparent knowledge of the syntax for config options which I can't find in any material from the mod author. So I assume I'm missing *something* (possibly some kind of heavy standard among forge mods? That or no one produces reference configurations and there's a lot of word of mouth.).

Either way, I've been programming for over a decade and it's been several years since I've had quite this much trouble resolving ambiguity despite copious Ctl+F, Googling, Github searching, etc. So, what's the deal here?

**Comment by BlakeBr0** [comment]
All the config options should have comments that explain the syntax for complex config options.
