### ISSUE TITLE
not server comaptable(forge 1.14.4)

### ISSUE THREAD

**Issue by SDUBZ** [BlakeBr0/PickleTweaks2#44]
14:50:01.033
Missing registry data for network connection:
	minecraft:recipe_serializer: pickletweaks:grid_repair
	minecraft:item: pickletweaks:emerald_pickaxe
	minecraft:item: pickletweaks:light_gray_cobblestone
	minecraft:item: pickletweaks:emerald_sword
	minecraft:item: pickletweaks:emerald_helmet
	minecraft:item: pickletweaks:flint_shears
	minecraft:item: pickletweaks:charcoal_piece
	minecraft:item: pickletweaks:emerald_axe
	minecraft:item: pickletweaks:green_cobblestone
	minecraft:item: pickletweaks:stone_paxel
	minecraft:item: pickletweaks:magnet
	minecraft:item: pickletweaks:coal_piece
	minecraft:item: pickletweaks:light_blue_cobblestone
	minecraft:item: pickletweaks:orange_cobblestone
	minecraft:item: pickletweaks:flint_paxel
	minecraft:item: pickletweaks:golden_paxel
	minecraft:item: pickletweaks:grass_fiber
	minecraft:item: pickletweaks:flint_leggings
	minecraft:item: pickletweaks:emerald_leggings
	minecraft:item: pickletweaks:flint_boots
	minecraft:item: pickletweaks:flint_hoe
	minecraft:item: pickletweaks:white_cobblestone
	minecraft:item: pickletweaks:grass_fiber_mesh
	minecraft:item: pickletweaks:yellow_cobblestone
	minecraft:item: pickletweaks:cyan_cobblestone
	minecraft:item: pickletweaks:emerald_hoe
	minecraft:item: pickletweaks:lime_cobblestone
	minecraft:item: pickletweaks:emerald_chestplate
	minecraft:item: pickletweaks:flint_chestplate
	minecraft:item: pickletweaks:diamond_apple
	minecraft:item: pickletweaks:emerald_apple
	minecraft:item: pickletweaks:emerald_paxel
	minecraft:item: pickletweaks:diamond_paxel
	minecraft:item: pickletweaks:iron_paxel
	minecraft:item: pickletweaks:watering_can
	minecraft:item: pickletweaks:wooden_paxel
	minecraft:item: pickletweaks:brown_cobblestone
	minecraft:item: pickletweaks:black_cobblestone
	minecraft:item: pickletweaks:night_vision_goggles
	minecraft:item: pickletweaks:emerald_boots
	minecraft:item: pickletweaks:red_cobblestone
	minecraft:item: pickletweaks:reinforced_night_vision_goggles
	minecraft:item: pickletweaks:magenta_cobblestone
	minecraft:item: pickletweaks:reinforced_mesh
	minecraft:item: pickletweaks:gray_cobblestone
	minecraft:item: pickletweaks:flint_helmet
	minecraft:item: pickletweaks:flint_axe
	minecraft:item: pickletweaks:purple_cobblestone
	minecraft:item: pickletweaks:flint_shovel
	minecraft:item: pickletweaks:dark_glass
	minecraft:item: pickletweaks:mesh
	minecraft:item: pickletweaks:flint_sword
	minecraft:item: pickletweaks:emerald_shovel
	minecraft:item: pickletweaks:blue_cobblestone
	minecraft:item: pickletweaks:flint_pickaxe
	minecraft:item: pickletweaks:pink_cobblestone
	minecraft:block: pickletweaks:light_blue_cobblestone
	minecraft:block: pickletweaks:magenta_cobblestone
	minecraft:block: pickletweaks:orange_cobblestone
	minecraft:block: pickletweaks:gray_cobblestone
	minecraft:block: pickletweaks:lime_cobblestone
	minecraft:block: pickletweaks:purple_cobblestone
	minecraft:block: pickletweaks:light_gray_cobblestone
	minecraft:block: pickletweaks:dark_glass
	minecraft:block: pickletweaks:green_cobblestone
	minecraft:block: pickletweaks:brown_cobblestone
	minecraft:block: pickletweaks:white_cobblestone
	minecraft:block: pickletweaks:black_cobblestone
	minecraft:block: pickletweaks:blue_cobblestone
	minecraft:block: pickletweaks:yellow_cobblestone
	minecraft:block: pickletweaks:cyan_cobblestone
	minecraft:block: pickletweaks:pink_cobblestone
	minecraft:block: pickletweaks:red_cobblestone
14:50:01.033
Failed to load registry, closing connection.
14:50:01.034
Connection closed, not continuing handshake

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/BlakeBr0/PickleTweaks/files/3817789/latest.log)

**Comment by SDUBZ** [comment]
bump @BlakeBr0 🤔

**Comment by BlakeBr0** [comment]
This shouldn't be an issue anymore.
