### ISSUE TITLE
Watering cans don't seem to work in 1.15 version

### ISSUE THREAD

**Issue by Sabster** [BlakeBr0/PickleTweaks2#48]
You can't fill them.

I did a search for previous issues - did find one; but it looks like it was for 1.14.

**Comment by BlakeBr0** [comment]
It works if you click on a block with water above it. I'll have to look into how to get it to always work though.

**Comment by Sabster** [comment]
I wonder if that's what happened:  I restarted into single player and it was full, so I haven't had any further issues since then.  Thanks and keep up the great work!

**Comment by ClaudiusMinimus** [comment]
In this example I have tried to fill the watering can by clicking on the block below from the top down to the block below and cannot get it to work. PickleTweaks-1.15.2-4.0.1.jar
![2020-03-20_13 19 35](https://user-images.githubusercontent.com/17887664/77198953-9af73480-6aad-11ea-87de-af4c2c6c887f.png)

**Comment by ClaudiusMinimus** [comment]
Thanks, this is fixed!
CM
