### ISSUE TITLE
[1.12.2] [Enhancement] Add Tooltips to tools from other mods

### ISSUE THREAD

**Issue by Kenja-mc** [BlakeBr0/PickleTweaks2#54]
Hey, sorry if you're not developing for 1.12 anymore, but I was making a modpack and I noticed that while some mods like _Thermal Foundation_ have support for tooltips, some other mods don't.

As you can see here, the Constantan hammer from _Thermal Foundation_ has a tooltip:
![image](https://i.imgur.com/RXUZFmq.png)

However, my modpack is using _Sparks Tools_, and the tooltip does not show:
![image](https://i.imgur.com/bPbZ1KU.png)

It would be convenient if there was a setting in the config file to add tooltips to tools that don't have them.

**Comment by BlakeBr0** [comment]
The tooltips should show up on anything that extends from the vanilla tool class. Also, I'm not updating the 1.12 version anymore.
