### ISSUE TITLE
Calculated repair

### ISSUE THREAD

**Issue by bolte-io** [BlakeBr0/PickleTweaks2#55]
Hey,

More of a feature suggestion.
When I try and repair an item, it only seems to count 1 item for a slight repair.
It would be better if I put more than 1 ingredient in with the tool for it to repair to the amount of ingredients I place.

i.e; If my tool is 75% damaged and my repair setting is 4, then I should be able to put 3x ingredient in with the tool and have it be fully repaired when I take it out of the crafting grid.

At the moment to do a full repair I have to put 1x ingredient in, take the tool and put it back in the grid again to repair even more. QOL issue really I know.

**Comment by BlakeBr0** [comment]
This is already how it works.

**Comment by bolte-io** [comment]
Then in the below screenshot, the result should be a fully repaired pickaxe with 64 gold in the crafting grid, or am I muss-understanding the feature?

![Repair](https://user-images.githubusercontent.com/51535687/88471577-e52c6e80-cf02-11ea-8cc6-b9997e8bbcf7.png)

**Comment by BlakeBr0** [comment]
You use multiple slots.

**Comment by bolte-io** [comment]
Like this?

![Repair](https://user-images.githubusercontent.com/51535687/88471789-faa29800-cf04-11ea-99f1-20d2a4eb9f3e.png)

**Comment by BlakeBr0** [comment]
Yeah like that. What version are you using? I don't remember ever seeing this feature not work before.

**Comment by bolte-io** [comment]
Now I know it's potentially a bug rather than a missing feature, I will investigate further by stripping the pack down to minimal and retesting, however I don't really have any content mods, just performance enhancing mods and JEI.

I am using 1.12.2, latest Forge available 14.23.5.2854.
I reduced the setup to just your mod and cucumber, and it now works as expected when putting multiple ingots surrounding the pickaxe.

Just a question, but why can you not have it calculate with a number of ingots on the same slot?
I have no idea which mod would be interfering with this process tbh. I have no content mods, so now I have to build this back up and re-test until I find the culprit.

![Now](https://user-images.githubusercontent.com/51535687/88476589-600c7e00-cf31-11ea-870d-6b8f68f98be1.png)

**Comment by bolte-io** [comment]
I have found the culprit, it is Fast Workbench, soon as that mod is introduced it causes this issue.
FastWorkbench-1.7.3

EDIT: It still does not work where the repair is multiplied by the ingredient placed in the same slot, however, if that was how it should work.

**Comment by BlakeBr0** [comment]
That's good to know. I never would've figured that out myself since I always just used the inventory crafting grid for repairs. The reason I'm not going to make it take multiple items from one slot is that it's not consistent with the rest of the recipes in the game and because of that I don't think it would be as intuitive.

**Comment by bolte-io** [comment]
I have seen it work that way with other mods, but from my point of view, it's actually more convenient to right click and deposit them one by one in place on the grid, but it's not so difficult just to right click drag out a shape. Just is my preference, maybe just have the option and toggle it in the config.

What do you plan to do about the incompatibility with Fast Workbench? Reason I ask is there are a lot of dependents on Fast Workbench, so a lot of modpacks use it.

**Comment by BlakeBr0** [comment]
I don't plan to do anything as weird incompatibilities like this are bound to happen when cutting corners for performance.
