### ISSUE TITLE
[1.12.2] Modded Tool Repair - The Betweelands

### ISSUE THREAD

**Issue by MokahTGS** [BlakeBr0/PickleTweaks2#56]
I'm having trouble using weedwood to repair a weedwood axe from Betweenlands.  Is mod support not there out of the box?  I seem to remember being able to do this in the past and I'm wondering if I need to add something to the configs to make this work.  I'm making a modpack that mixes mods a bit so getting this to work would be useful.

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge:2854
 - Cucumber:1.1.3
 - Pickle Tweaks:2.1.3

**Comment by BlakeBr0** [comment]
Whatever would work on a normal anvil should work out of the box with the grid repairing. You can also add custom repair materials in the config file.

**Comment by MokahTGS** [comment]
Can I get some guidance as to how I'd add weed wood tools?
