### ISSUE TITLE
Tools/weapons destroyed when out of durability irrelevant of config setting.

### ISSUE THREAD

**Issue by CcytherR** [BlakeBr0/PickleTweaks2#62]
- Minecraft: 1.16.3
 - Forge: 34.1.17 tested with different forge versions including recommended and latest
 - Cucumber:1.16.3-4.1.2
 - Pickle Tweaks: 1.16.3-5.1.2
Tools break when out of durability even though the config said not to on the latest 1.16.3 version.
Also is it normal for the axe to break if you kill mobs with it in older versions for mc 1.12 with the latest forge, and pickle tweaks and cucumber for mc 1.12.2

Thanks.

**Comment by BlakeBr0** [comment]
I am unable to reproduce this.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity.
