### ISSUE TITLE
Tools do not break

### ISSUE THREAD

**Issue by emanuele246gi** [BlakeBr0/PickleTweaks2#64]
**Describe the bug**
Tools do not break even if I change the config file of repairing tools from true to false.

**To Reproduce**
1. Go to the config file
2. Change every settings you need (toolBreaking to true, Crafting Grid Tool Repairing to false, etc.)
3. Open the game and join a world
4. Use a tool to its breaking time

**Expected behavior**
I expected the tool to break, but it's still there waiting to be repaired.

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Forge: 31.2.47
 - Cucumber: 3.0.9
 - Pickle Tweaks: 4.0.4

**Comment by BlakeBr0** [comment]
Those two options aren't correlated. You would have to set `toolBreaking = false` to disable the tool breaking tweak.
