### ISSUE TITLE
1 simple trick to GROW your tree (or not because this is a bug report)

### ISSUE THREAD

**Issue by Darkosto** [BlakeBr0/PickleTweaks2#65]
**Describe the bug**
When using a watering can to grow a sapling, only the bottom log will appear. The rest of the tree does grow, but it's invisible. Leaving the world and reloading will show the entire tree. I loaded up with only pickle tweaks and cucumber and still was able to reproduce.

**To Reproduce**

They taught me reproduction in biology but since that was like 16 years ago I have forgotten. I have failed you. I do remember it being icky though. So, there's that.

**Expected behavior**

Well, I was hoping that I would be delivered an entire tree. In fact, I prepaid for that whole tree and I got a single log. I find that your inability to deliver a promised full tree is deterimental to my enjoyment of Christmas. I am not happy that I paid for the full-tree DLC. Please fix. Or I will have to report you to the authorities. Also, 1.17 mc when????????

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/10309699/102561946-d3eb2680-408a-11eb-8b56-181e838b5f93.png)

![image](https://user-images.githubusercontent.com/10309699/102561970-e6656000-408a-11eb-8799-12840b10321a.png)

https://clips.twitch.tv/PrettyElatedSheepLitFam <---- Video of the crime.

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.12
 - Cucumber: 4.1.5
 - Pickle Tweaks: 5.1.4

**Comment by BlakeBr0** [comment]
Same issue as https://github.com/BlakeBr0/PickleTweaks/issues/60. I haven't had much luck with this issue so far.
