### ISSUE TITLE
Config to set up what items can be broken with paxel

### ISSUE THREAD

**Issue by Morningate** [BlakeBr0/PickleTweaks2#66]
**Is your feature request related to a problem? Please describe.**
Sort of. It isn't a bug, but many times I encounter items that can't be broken correctly with the paxel. In those cases, a stone axe is faster than a diamond or emerald paxel. It's as though the item doesn't recognize the paxel as the proper tool. This most often happens with items introduced by another mod. (Examples are the alternate jack o' lanterns from Oh My Gourd! and the rack storage item from Minecolonies.)

**Describe the solution you'd like**
Is it possible to set up a section of the config file that tells the game which items a paxel can break? Having a "whitelist" option for paxel-breakable items would reduce the need for you to address compatibility issues with every mod out there, but I'm not sure if the game's code would allow for this.

**Describe alternatives you've considered**
Alternatively, the paxel will need to be adjusted so that it is recognized by all items requiring either an axe, pickaxe, or shovel to break, regardless of where those items come from.

Thank you very much for this mod. It's an essential part of my minecraft experience.

**Comment by BlakeBr0** [comment]
Any block that has proper required tools set should work fine since the paxel has all 3 tool types. My guess is there's some materials that don't get accounted for, so I'll look into that. I don't see the value in adding a config option for this either way.
