### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by TheYoloPanda** [BlakeBr0/PickleTweaks2#74]
**Describe the bug**
With the latest update, every time I try to run minecraft it crashes

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.5
 - Cucumber: 4.1.10
 - Pickle Tweaks: 5.2.4
[crash-2021-09-27_14.38.03-fml.txt](https://github.com/BlakeBr0/PickleTweaks/files/7236257/crash-2021-09-27_14.38.03-fml.txt)

**Comment by Darkosto** [comment]
I'm getting an error too. I wanted to include mine just in case it provides any new info:

https://pastebin.com/DLYbMmMP
