### ISSUE TITLE
How consume item without reduce durability ?

### ISSUE THREAD

**Issue by MickeyMouseYT** [BlakeBr0/PickleTweaks2#76]
Hello, how did I consume an item on kubejs because I have an item problem that has durability so how do i consume items without reduce durability ?

---

Kubejs :

event.shaped(item.of('pickletweaks:mesh',1), ['scs','cgc','scs'],{g: 'pickletweaks:grass_fiber_mesh', s: 'minecraft:stick', c: 'minecraft:string',})

event.shaped(item.of('waterstrainer:string_mesh',1), ['sss','sps','sss'],{s: 'minecraft:string', p: 'pickletweaks:mesh',})

---

i want : "pickletweaks:mesh" and "pickletweaks:grass_fiber_mesh" are now consomed item but no reduce durability. 

Thank you.

MickeyMouseYT

**Comment by MickeyMouseYT** [comment]
@BlakeBr0

**Comment by BlakeBr0** [comment]
If there is a way to specify the container item for recipe ingredients (like the ingredient transformers in crafttweaker), you would be able to set it to minecraft:air to have it return nothing. I've never used kubejs so I'm not sure what functionality it has.
