### ISSUE TITLE
[1.18-Forge] Game doesn't start when PickleTweaks + Cucumber is installed.

### ISSUE THREAD

**Issue by Gbergz** [BlakeBr0/PickleTweaks2#78]
**Describe the bug**
Game doesn't start when PickleTweaks + Cucumber is installed.
(encountered an error during the common_setup event phase.)
(net.minecraft.worlditem.Item$Properties)

**To Reproduce**
1. Install PickleTweaks + Cucumber
2. Start game.
3. Crash / fails to load.
4. Profit.

**Expected behavior**
That the game is starting up correctly and is playable w/ PickleTweaks + Cucumber.

**Screenshots / Scripts / Logs**
latest.log: https://gist.github.com/Gbergz/a772db1eade7f26931c552f04d870a71
crash-report: https://gist.github.com/Gbergz/6dbededf00e1b34e999416eec0e8a208
screenshot: 
![image](https://user-images.githubusercontent.com/26634554/145678592-3e294b43-4240-4491-9c2d-0d7c844f55ef.png)

**Versions:**
 - Minecraft: 1.18
 - Forge: 38.0.17
 - Cucumber: 5.0.0 | https://www.curseforge.com/minecraft/mc-mods/cucumber/files/3559205
 - Pickle Tweaks: 6.0.0 | https://www.curseforge.com/minecraft/mc-mods/pickle-tweaks/files/3559229

**Comment by BlakeBr0** [comment]
Should be fixed with Cucumber 5.0.1
