### ISSUE TITLE
Flint paxel mines obsidian

### ISSUE THREAD

**Issue by jstansel** [BlakeBr0/PickleTweaks2#79]
**Describe the bug**
Flint paxel mines obsidian

**To Reproduce**
1. Obtain a flint paxel
2. Look at an obsidian block and note that the one probe shows a green checkmark
2. Use the paxel to break the obsidian block
3. The obsidian block drops obsidian

**Expected behavior**
1. I expect the obsidian block to not drop anything because the flint paxel mining level is only iron
2. I expect the one probe to show a red x because the mining level of the flint paxel is too low to mine obsidian

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.0.9
 - Cucumber: 5.0.1
 - Pickle Tweaks: 6.0.0

Please let me know if any further information is needed. Thanks for this mod!

**Comment by BlakeBr0** [comment]
This should be fixed with Cucumber version 5.0.2
