### ISSUE TITLE
config to disable shears (specific tool) from the mod completely

### ISSUE THREAD

**Issue by ninjacm** [BlakeBr0/PickleTweaks2#80]
**Is your feature request related to a problem? Please describe.**
Shears do not break because of the grid repair option, however I am unable to repair shears.

**Describe the solution you'd like**
Either an option in the config to blacklist some tools from the mod entirely, or option to remove shears from the tool list for grid repair

**Describe alternatives you've considered**
I tried adding an override similar to others I have added(i.e Construction Wands i used the override to specify only 1 repair item needed to repair them since they only take 1 [stone/iron/diamond] to craft), but this also does not work, as shears seem to not be repairable at all

**Additional context**

**Comment by BlakeBr0** [comment]
I think I'm going to make it so shears can be repaired at half cost like shovels.

**Comment by BlakeBr0** [comment]
I just tested and was able to make shears repairable by adding `"minecraft:shears=minecraft:iron_ingot"`. 

I think I'll add overrides for shears by default and add that cheaper shears config option I mentioned before.
