### ISSUE TITLE
Night vision goggles no longer work in 1.19.1

### ISSUE THREAD

**Issue by szucconi** [BlakeBr0/PickleTweaks2#81]
Forge 42.0.1. Using either night vision goggle in either the head slot didnt illuminate the world. The night vision effect wasnt put on the player.

**Comment by BlakeBr0** [comment]
Are you still facing this issue? The goggles seemed to work when I tested them.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
