### ISSUE TITLE
Paxels break if stripping logs

### ISSUE THREAD

**Issue by OverWims** [BlakeBr0/PickleTweaks2#82]
When holding the paxel, if you strip logs (tested with cherry from Biomes O' Plenty) the paxel will just break completely.

Versions:
 - Minecraft: 1.18.2
 - Forge: 40.1.85
 - Cucumber: 5.1.3
 - Pickle Tweaks: 6.1.1

**Comment by BlakeBr0** [comment]
Is it just BOP logs specifically? I quickly tested with oak logs and it seemed to work properly

**Comment by BlakeBr0** [comment]
Nevermind, I see what you mean.

**Comment by OverWims** [comment]
yeah I just tested myself and it did it with birch too
