### ISSUE TITLE
Stone paxel cannot be repaired in the inventory

### ISSUE THREAD

**Issue by kayrablob** [BlakeBr0/PickleTweaks2#83]
Stone paxel cannot be repaired with cobblestone using the Crafting Grid Tool Repair feature, Was working as intended before

Steps to reproduce the behavior: None, it stopped working out of nowhere after i logged in normally

**Expected behavior**
For the stone paxel to be repaired in the inventory

**Versions (please complete the following information):**
 - Minecraft:1.19.2
 - Forge:43.2.14
 - Cucumber:6.0.7
 - Pickle Tweaks:7.0.3

**Comment by BlakeBr0** [comment]
I just tested and it seems to work for me. Is this still an issue you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
