### ISSUE TITLE
Repair don't work

### ISSUE THREAD

**Issue by Merondaar** [BlakeBr0/PickleTweaks2#84]
I've installed Pickle Tweak on a modpack and the crafting grid tool repair just don't work. I've looked at the configs but all is good so I don't have a single hint of why it don't work. All the other stuff is good except for the repair. Are there conflicts with other mods like Quark or Supplementaries ? I've searched for two days and didn't find anything.

**To Reproduce**
I don't know, it just don't work

**Expected behavior**
crafting grid tool repair work

**Versions:**
 - Minecraft: 1.18.2
 - Forge: 40.2.10
 - Cucumber: 5.1.4
 - Pickle Tweaks: 6.1.2

**Comment by BlakeBr0** [comment]
I did a quick test and it seems like I can repair a Stone Pickaxe with Cobblestone. Does that work for you? If not there may be some sort of configuration or compatibility issue but I'm not too sure.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
