### ISSUE TITLE
Add a Tag for Coloured Cobblestone

### ISSUE THREAD

**Issue by TheBedrockMaster** [BlakeBr0/PickleTweaks2#90]
**Describe the solution you'd like**

A tag that can be added to all 16 varieties of coloured cobblestone, for example: `pickletweaks:colored_cobblestone`.

I don't want to manually add EMC to them all in 9sky 🤣

**Comment by BlakeBr0** [comment]
Added in version 8.0.4 (and 9.0.0 for 1.21).
